todo-app
├── backend
│   ├── src
│   │   └── main.rs
│   ├── Cargo.toml
│   └── README.md
├── frontend
│   ├── src
│   │   ├── components
│   │   │   ├── TaskForm.tsx
│   │   │   ├── TaskList.tsx
│   │   │   └── Task.tsx
│   │   ├── services
│   │   │   └── api.ts
│   │   ├── types
│   │   │   └── index.ts
│   │   ├── App.tsx
│   │   └── main.tsx
│   ├── package.json
│   ├── tsconfig.json
│   └── README.md
└── README.md